### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pentacular** [DanielLiamAnderson/Packaide#1]
Hello, I couldn't find a license on this project.

I assume it's GPL to comply with CGAL, but it would be nice to make it explicit. :)

Thanks.

**Comment by snagappa** [comment]
Hello, I just wanted to check if you're able to confirm what license this is released under.
Thanks!

**Comment by DanielLiamAnderson** [comment]
Sorry for the delay, I missed the first issue post. It should indeed be GPL to be compatible with CGAL.
